MY_TARGET_SRCS+=SampleApp.cpp

SA_BASE_DIR=app
SA_BASE_SRC_DIR=$(SA_BASE_DIR)/src

## APPLICATION SOURCES
SA_SOURCES=SampleApp.cpp

SA_INCLUDES=$(SA_BASE_SRC_DIR)/include

VPATH+=$(SA_BASE_SRC_DIR)

SA_OBJECTS=$(SA_SOURCES:.cpp=.o)

## SPECIFY YOUR INCLUDE DIRECTORIES THE COMPILER WILL SEARCH THROUGH
MY_INCLUDES+=$(addprefix -I,$(SA_INCLUDES))

SampleApp: $(SA_OBJECTS) $(BSW_OBJECTS)
	$(LD) $(CXXFLAGS) -o $(BIN_DIR)/$@ $(addprefix $(OBJ_DIR)/,$^) $(LDFLAGS)