MY_TARGET_SRCS+=XcpLinux.cpp

XCPLINUX_BASE_DIR=app/XcpLinux
XCPLINUX_BASE_SRC_DIR=$(XCPLINUX_BASE_DIR)/src

## APPLICATION SOURCES 
XCPLINUX_SOURCES=XcpLinux.cpp

XCPLINUX_INCLUDES=$(XCPLINUX_BASE_DIR)/include

VPATH+=$(XCPLINUX_BASE_SRC_DIR)

XCPLINUX_OBJECTS=$(XCPLINUX_SOURCES:.cpp=.o)

## SPECIFY YOUR INCLUDE DIRECTORIES THE COMPILER WILL SEARCH THROUGH
MY_INCLUDES+=$(addprefix -I,$(XCPLINUX_INCLUDES))

XcpLinux: $(XCPLINUX_OBJECTS) $(BSW_OBJECTS)
	$(LD) $(CXXFLAGS) -o $(BIN_DIR)/$@ $(addprefix $(OBJ_DIR)/,$^) $(LDFLAGS)